[build]
  command = "echo 'Building clash-web-converter for Netlify'"
  publish = "public"
  
[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/sub/*"
  to = "/.netlify/functions/subscribe"
  status = 200

[[redirects]]
  from = "/download/*"
  to = "/.netlify/functions/download"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9" 